services:
  eir-frontend:
    build: ./eir-frontend
    container_name: eir-frontend
    ports:
      - "8090:80"
    restart: unless-stopped
    networks:
      - app_net

  eir-backend:
    build: ./eir-backend
    container_name: eir-backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
logging:
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"